# Site settings
title: 不忘初心，上下求索。
email: zzuieliyaoli@gmail.com
description: "一个博客，涉及技术、吐槽、思考。 "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liyaoli.com" # the base hostname & protocol for your site
github_username:  zzuieliyaoli
disqus: zzuieliyaoli
paginate: 10000
paginate_path: "blog/page:num/"
# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title.html
plugins: [jekyll-paginate]
highlighter: rouge
